const CountryCodesTable = {
  GB: ["United Kingdom"],
  AD: ["Andorra"],
  AE: ["United Arab Emirates"],
  AF: ["Afghanistan"],
  AG: ["Antigua and Barbuda"],
  AI: ["Anguilla"],
  AL: ["Albania"],
  AM: ["Armenia"],
  AO: ["Angola"],
  AQ: ["Antarctica"],
  AR: ["Argentina"],
  AS: ["American Samoa"],
  AT: ["Austria"],
  AU: ["Australia"],
  AW: ["Aruba"],
  AX: ["Aland Islands"],
  AZ: ["Azerbaijan"],
  BA: ["Bosnia and Herzegovina"],
  BB: ["Barbados"],
  BD: ["Bangladesh"],
  BE: ["Belgium"],
  BF: ["Burkina Faso"],
  BG: ["Bulgaria"],
  BH: ["Bahrain"],
  BI: ["Burundi"],
  BJ: ["Benin"],
  BL: ["Saint Barthélemy", "Saint Barthelemy"],
  BM: ["Bermuda"],
  BN: ["Brunei"],
  BO: ["Bolivia"],
  BQ: ["Caribbean Netherlands"],
  BR: ["Brazil"],
  BS: ["Bahamas"],
  BT: ["Bhutan"],
  BV: ["Bouvet Island"],
  BW: ["Botswana"],
  BY: ["Belarus"],
  BZ: ["Belize"],
  CA: ["Canada"],
  CC: ["Cocos Islands", "Keeling Islands"],
  CD: ["Democratic Republic of the Congo"],
  CF: ["Central African Republic"],
  CG: ["Congo", "Republic of Congo"],
  CH: ["Switzerland"],
  CI: ["Côte d'Ivoire", "Ivory Coast"],
  CK: ["Cook Islands"],
  CL: ["Chile"],
  CM: ["Cameroon"],
  CN: ["China"],
  CO: ["Colombia"],
  CR: ["Costa Rica"],
  CU: ["Cuba"],
  CV: ["Cape Verde"],
  CW: ["Curaçao"],
  CX: ["Christmas Island"],
  CY: ["Cyprus"],
  CZ: ["Czech Republic"],
  DE: ["Germany"],
  DJ: ["Djibouti"],
  DK: ["Denmark"],
  DM: ["Dominica"],
  DO: ["Dominican Republic"],
  DZ: ["Algeria"],
  EC: ["Ecuador"],
  EE: ["Estonia"],
  EG: ["Egypt"],
  EH: ["Western Saharan"],
  ER: ["Eritrea"],
  ES: ["Spain"],
  ET: ["Ethiopia"],
  FI: ["Finland"],
  FJ: ["Fiji"],
  FK: ["Falkland Islands", "Malvinas Islands"],
  FM: ["Micronesia"],
  FO: ["Faroe Islands"],
  FR: ["France"],
  GA: ["Gabon"],
  GD: ["Grenada"],
  GE: ["Georgia"],
  GF: ["French Guiana"],
  GG: ["Guernsey"],
  GH: ["Ghana"],
  GI: ["Gibralter"],
  GL: ["Greenland"],
  GM: ["Gambia"],
  GN: ["Guinea"],
  GP: ["Guadeloupe"],
  GQ: ["Equatorial Guinea"],
  GR: ["Greece"],
  GS: ["South Georgia and the South Sandwich Islands"],
  GT: ["Guatemala"],
  GU: ["Guam"],
  GW: ["Guinea-Bissau", "Guinea - Bissau", "Bissau"],
  GY: ["Guyana"],
  HK: ["Hong Kong"],
  HM: ["Heard and McDonald Islands"],
  HN: ["Honduras"],
  HR: ["Croatia"],
  HT: ["Haiti"],
  HU: ["Hungary"],
  ID: ["Indonesia"],
  IE: ["Ireland"],
  IL: ["Israel"],
  IM: ["Isle of Man"],
  IN: ["India"],
  IO: ["British Indian Ocean Territory"],
  IQ: ["Iraq"],
  IR: ["Iran"],
  IS: ["Iceland"],
  IT: ["Italy"],
  JE: ["Jersey"],
  JM: ["Jamaica"],
  JO: ["Jordan"],
  JP: ["Japan"],
  KE: ["Kenya"],
  KG: ["Kyrgyzstan"],
  KH: ["Cambodia"],
  KI: ["Kiribati"],
  KM: ["Comoros"],
  KN: ["Saint Kitts and Nevis"],
  KP: ["North  Korea"],
  KR: ["South Korea"],
  KW: ["Kuwait"],
  KY: ["Cayman Islands"],
  KZ: ["Kazakhstan"],
  LA: ["Laos"],
  LB: ["Lebanon"],
  LC: ["Saint Lucia"],
  LI: ["Liechtenstein"],
  LK: ["Sri Lanka"],
  LR: ["Liberia"],
  LS: ["Lesotho"],
  LT: ["Lithuania"],
  LU: ["Luxembourg"],
  LV: ["Latvia"],
  LY: ["Libya"],
  MA: ["Morocco"],
  MC: ["Monaco"],
  MD: ["Moldova"],
  ME: ["Montenegro"],
  MF: ["Saint Martin(France)", "Saint Martin"],
  MG: ["Madagascar"],
  MH: ["Marshall Islands", "Marshalls"],
  MK: ["Macedonia"],
  ML: ["Mali"],
  MM: ["Burma", "Republic of the Union of Myanmar", "Myanmar"],
  MN: ["Mongolia"],
  MO: ["Macau"],
  MP: ["Northern Mariana Islands"],
  MQ: ["Martinique"],
  MR: ["Mauritania"],
  MS: ["Montserrat"],
  MT: ["Malta"],
  MU: ["Mauritius"],
  MV: ["Maldives"],
  MW: ["Malawi"],
  MX: ["Mexico"],
  MY: ["Malaysia"],
  MZ: ["Mozambique"],
  NA: ["Namibia"],
  NC: ["New Caledonia"],
  NE: ["Niger"],
  NF: ["Norfolk Island"],
  NG: ["Nigeria"],
  NI: ["Nicaragua"],
  NL: ["Netherlands"],
  NO: ["Norway"],
  NP: ["Nepal"],
  NR: ["Nauru"],
  NU: ["Niue"],
  NZ: ["New Zealand"],
  OM: ["Oman"],
  PA: ["Panama"],
  PE: ["Peru"],
  PF: ["French Polynesia", "Polynesia"],
  PG: ["Papua New Guinea", "Papua", "New Guinea"],
  PH: ["Philippines"],
  PK: ["Pakistan"],
  PL: ["Poland"],
  PM: ["Saint Pierre and Miquelon", "St. Pierre and Miquelon"],
  PN: ["Pitcairn"],
  PR: ["Puerto Rico"],
  PS: ["Palestine"],
  PT: ["Portugal"],
  PW: ["Palau"],
  PY: ["Paraguay"],
  QA: ["Qatar"],
  RE: ["Réunion"],
  RO: ["Romania"],
  RS: ["Serbia"],
  RU: ["Russian Federation", "Russia"],
  RW: ["Rwanda"],
  SA: ["Saudi Arabia"],
  SB: ["Solomon Islands"],
  SC: ["Seychelles"],
  SD: ["Sudan"],
  SE: ["Sweden"],
  SG: ["Singapore"],
  SH: ["Saint Helena"],
  SI: ["Slovenia"],
  SJ: ["Svalbard and Jan Mayen Islands"],
  SK: ["Slovakia"],
  SL: ["Sierra Leone"],
  SM: ["San Marino"],
  SN: ["Senegal"],
  SO: ["Somalia"],
  SR: ["Suriname"],
  SS: ["South Sudan"],
  ST: ["São Tome and Príncipe"],
  SV: ["El Salvador"],
  SX: ["Saint Martin(Netherlands)", "Saint Martin of Netherlands"],
  SY: ["Syria"],
  SZ: ["Swaziland"],
  TC: ["Turks and Caicos Islands"],
  TD: ["Chad"],
  TF: ["French Southern Territories"],
  TG: ["Togo"],
  TH: ["Thailand"],
  TJ: ["Tajikistan"],
  TK: ["Tokelau"],
  TL: ["Timor", "Timor - Leste"],
  TM: ["Turkmenistan"],
  TN: ["Tunisia"],
  TO: ["Tonga"],
  TR: ["Turkey"],
  TT: ["Trinidad and Tobago"],
  TV: ["Tuvalu"],
  TW: ["Taiwan"],
  TZ: ["Tanzania"],
  UA: ["Ukraine"],
  UG: ["Uganda"],
  UM: ["United States Minor Outlying Islands"],
  US: ["United States of America", "United States"],
  UY: ["Uruguay"],
  UZ: ["Uzbekistan"],
  VA: ["Vatican"],
  VC: ["Saint Vincent and Grenadines"],
  VE: ["Venezuela"],
  VG: ["British Virgin Islands"],
  VI: ["United States Virgin Islands"],
  VN: ["Vietnam"],
  VU: ["Vanuatu"],
  WF: ["Wallis and Futuna Islands"],
  WS: ["Samoa"],
  YE: ["Yemen"],
  YT: ["Mayotte"],
  ZA: ["South Africa"],
  ZM: ["Zambia"],
  ZW: ["Zimbabwe"]
};

const CountryCodesList = [
  "GB",
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AX",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BQ",
  "BR",
  "BS",
  "BT",
  "BV",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CC",
  "CD",
  "CF",
  "CG",
  "CH",
  "CI",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "EH",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FO",
  "FR",
  "GA",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GP",
  "GQ",
  "GR",
  "GS",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HM",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IO",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KI",
  "KM",
  "KN",
  "KP",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NE",
  "NF",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NR",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PH",
  "PK",
  "PL",
  "PM",
  "PN",
  "PR",
  "PS",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SX",
  "SY",
  "SZ",
  "TC",
  "TD",
  "TF",
  "TG",
  "TH",
  "TJ",
  "TK",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TW",
  "TZ",
  "UA",
  "UG",
  "UM",
  "US",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WF",
  "WS",
  "YE",
  "YT",
  "ZA",
  "ZM",
  "ZW"
];

export { CountryCodesList, CountryCodesTable };
